### ISSUE TITLE
`make test` fails inside Ubuntu container

### ISSUE THREAD

**Issue by srasku** [eclipse/mosquitto#1434]
`make test` is failing inside my container with the following error
```
root@b9b89712af63:/mosquitto# make test
set -e; for d in lib client src; do make -C ${d}; done
make[1]: Entering directory '/mosquitto/lib'
make -C cpp
make[2]: Entering directory '/mosquitto/lib/cpp'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/mosquitto/lib/cpp'
make[1]: Leaving directory '/mosquitto/lib'
...
cc -I../../../lib -I../../../src -Wall -Werror 08-tls-psk-pub.c -o 08-tls-psk-pub.test ../../../lib/libmosquitto.so.1
cc -I../../../lib -I../../../src -Wall -Werror 08-tls-psk-bridge.c -o 08-tls-psk-bridge.test ../../../lib/libmosquitto.so.1
make[3]: Leaving directory '/mosquitto/test/broker/c'
./01-connect-anon-denied.py
Traceback (most recent call last):
  File "./01-connect-anon-denied.py", line 22, in <module>
    broker = mosq_test.start_broker(filename=os.path.basename(__file__), use_conf=True, port=port)
  File "/mosquitto/test/mosq_test.py", line 52, in start_broker
    c = socket.create_connection(("localhost", port))
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
Makefile:23: recipe for target '01' failed
make[2]: *** [01] Error 1
make[2]: Leaving directory '/mosquitto/test/broker'
Makefile:10: recipe for target 'test' failed
make[1]: *** [test] Error 2
make[1]: Leaving directory '/mosquitto/test'
Makefile:75: recipe for target 'test' failed
make: *** [test] Error 2
```

I built the container using this `Dockerfile`:
```
FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
    git
    
RUN git clone https://github.com/eclipse/mosquitto.git

RUN apt-get update \
    && apt-get install -y \
    build-essential \
    libssl-dev \
    xsltproc

RUN sed -i -e 's/^\(WITH_DOCS:=\).*$/\1no/' mosquitto/config.mk

RUN cd mosquitto \
    && make

RUN apt-get install -y \
    libcunit1-dev \
    python3
```

**Comment by ralight** [comment]
There have been lots of improvements to the tests since this report, so I don't believe it is still an issue. The automated tests run just fine and likewise when run locally. I'm closing this issue, if it is still a problem for you please do reopen and add more details.
