### ISSUE TITLE
 Timed out as no activity, keepAlive=60,000 lastOutboundActivity=1,573,823,144,751 lastInboundActivity=1,573,823,084,811 time=1,573,823,204,751 lastPing=1,573,823,144,751 Client is not connected (32104)

### ISSUE THREAD

**Issue by 2422006980** [eclipse/mosquitto#1498]
i used version 1.4.8
Error reported after a period of normal operation
The error message is as follows

DEBUG 2019-11-15 21:06:43 - Updated cluster metadata version 7 to Cluster(id = q-QkeFo7SDOiypivbmLL8A, nodes = [192.168.1.76:19091 (id: 2 rack: null), 192.168.1.74:19091 (id: 0 rack: null), 192.168.1.75:19091 (id: 1 rack: null)], partitions = [])
ERROR 2019-11-15 21:06:44 - iotshadow_clientId: Timed out as no activity, keepAlive=60,000 lastOutboundActivity=1,573,823,144,751 lastInboundActivity=1,573,823,084,811 time=1,573,823,204,751 lastPing=1,573,823,144,751
Client is not connected (32104)
DEBUG 2019-11-15 21:06:44 - deliveryComplete---------true
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:166)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.subscribe(MqttAsyncClient.java:835)
        at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:322)
        at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:360)
        at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:337)
        at com.adups.iot.shadow.service.impl.MqttServiceImpl.subTopic(MqttServiceImpl.java:84)
        at com.adups.iot.shadow.service.impl.MqttServiceImpl.connect(MqttServiceImpl.java:69)
        at com.adups.iot.shadow.listener.MyMqttCallback.connectionLost(MyMqttCallback.java:27)
        at org.eclipse.paho.client.mqttv3.internal.CommsCallback.connectionLost(CommsCallback.java:269)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:385)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.handleRunException(ClientComms.java:752)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.checkForActivity(ClientComms.java:734)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.checkForActivity(ClientComms.java:718)
        at org.eclipse.paho.client.mqttv3.TimerPingSender$PingTask.run(TimerPingSender.java:77)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Timed out waiting for a response from the server (32000)
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
        at org.eclipse.paho.client.mqttv3.internal.ClientState.checkForActivity(ClientState.java:661)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.checkForActivity(ClientComms.java:732)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.checkForActivity(ClientComms.java:718)
        at org.eclipse.paho.client.mqttv3.TimerPingSender$PingTask.run(TimerPingSender.java:77)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
WARN  2019-11-15 21:06:44 - 连接断开：Timed out waiting for a response from the server，重连连接

Has anyone had this problem???

**Comment by 2422006980** [comment]
i can't sub message

**Comment by ralight** [comment]
None of your logs relate to Mosquitto. Are you sure you are asking in the right place?

**Comment by 2422006980** [comment]
Thank you for your answer. 
This problem will recover itself after a while. I'm not sure what caused it.
Each time this problem occurs, the topic I subscribed to receives a message but does not execute the messageArrived method.
Now there are about thousands of devices, possibly is that subscribe to news caused by too much, because I use the default mosquitto. Conf
