### ISSUE TITLE
4 tests fail in develop branch

### ISSUE THREAD

**Issue by schmidtw** [eclipse/mosquitto#2127]
I am running the tests on the `develop` branch & found that these 4 tests don't work on my Fedora 33 machine:

`test/lib/Makefile`:
```
	./03-publish-c2b-qos1-disconnect.py c/03-publish-c2b-qos1-disconnect.test
	./03-publish-c2b-qos2-disconnect.py c/03-publish-c2b-qos2-disconnect.test
	./03-publish-c2b-qos2-maximum-qos-1.py c/03-publish-c2b-qos2-maximum-qos-1.test
	./02-subscribe-qos1.py c/02-subscribe-qos1-async2.test
```

I made a small change to the Makefile to just run these tests:
```
test-failures :
	-./03-publish-c2b-qos1-disconnect.py c/03-publish-c2b-qos1-disconnect.test
	-./03-publish-c2b-qos2-disconnect.py c/03-publish-c2b-qos2-disconnect.test
	-./03-publish-c2b-qos2-maximum-qos-1.py c/03-publish-c2b-qos2-maximum-qos-1.test
	-./02-subscribe-qos1.py c/02-subscribe-qos1-async2.test
```

and get this output:
```
./03-publish-c2b-qos1-disconnect.py c/03-publish-c2b-qos1-disconnect.test
Traceback (most recent call last):
  File "/home/schmidtw/work/xmidt/mqtt/m3/test/lib/./03-publish-c2b-qos1-disconnect.py", line 49, in <module>
    (conn, address) = sock.accept()
  File "/usr/lib64/python3.9/socket.py", line 293, in accept
    fd, addr = self._accept()
socket.timeout: timed out
make: [Makefile:26: test-failures] Error 1 (ignored)
./03-publish-c2b-qos2-disconnect.py c/03-publish-c2b-qos2-disconnect.test
Traceback (most recent call last):
  File "/home/schmidtw/work/xmidt/mqtt/m3/test/lib/./03-publish-c2b-qos2-disconnect.py", line 49, in <module>
    (conn, address) = sock.accept()
  File "/usr/lib64/python3.9/socket.py", line 293, in accept
    fd, addr = self._accept()
socket.timeout: timed out
make: [Makefile:27: test-failures] Error 1 (ignored)
./03-publish-c2b-qos2-maximum-qos-1.py c/03-publish-c2b-qos2-maximum-qos-1.test
./02-subscribe-qos1.py c/02-subscribe-qos1-async2.test
connect_async failed: Connection refused
Traceback (most recent call last):
  File "/home/schmidtw/work/xmidt/mqtt/m3/test/lib/./02-subscribe-qos1.py", line 47, in <module>
    (conn, address) = sock.accept()
  File "/usr/lib64/python3.9/socket.py", line 293, in accept
    fd, addr = self._accept()
socket.timeout: timed out
make: [Makefile:29: test-failures] Error 1 (ignored)
```

The `./02-subscribe-qos1.py c/02-subscribe-qos1-async2.test` case has issues in 2.0.8 similar to #1659 .  I haven't had time to debug the other issues.

**Comment by ralight** [comment]
I think the issue you linked is unrelated. This should be fixed now, it was down to callbacks blocking each other. Thanks for the report!
