### ISSUE TITLE
Mosquitto v2.0.18 - unable to connect to server error

### ISSUE THREAD

**Issue by wangguan1888** [eclipse/mosquitto#3116]
**Problem:**
I am using client app mqtt.fx to connect mosquitto and it works well until yesterday. However, today unable to connect to server error is occured.
I tried the following but not work.
1.Restarted Mosquitto.
2.Restarted Server PC.
3.Changed firewall setting to open port 1883.
4.Mosquitto.conf is not changed.(listener 1883 , allow_anonymous true)

Error Log is shown as below. Could you please tell me how to resolve this problem? Thank you.
**Error Log:**
``
2024-09-27 17:20:22,607  INFO --- MqttFX ClientModel             : MqttClient with ID MQTT_FX_Client assigned.
2024-09-27 17:20:27,000 ERROR --- MqttFX ClientModel             : Error when connecting
org.eclipse.paho.client.mqttv3.MqttException: Unable to connect to server
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:94) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:701) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_181]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[?:1.8.0_181]
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[?:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_181]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_181]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_181]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_181]
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:84) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	... 8 more
2024-09-27 17:20:27,005 ERROR --- MqttFX ClientModel             : Please verify your Settings (e.g. Broker Address, Broker Port & Client ID) and the user credentials!
org.eclipse.paho.client.mqttv3.MqttException: Unable to connect to server
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:94) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:701) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_181]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[?:1.8.0_181]
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[?:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_181]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_181]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_181]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_181]
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:84) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	... 8 more
2024-09-27 17:20:27,010  INFO --- ScriptsController              : Clear console.
2024-09-27 17:20:27,010 ERROR --- BrokerConnectService           : Unable to connect to server

``

**Comment by Daedaluz** [comment]
`Caused by: java.net.ConnectException: Connection refused: connect`

Connection refused usually means the server isn't running?
