### ISSUE TITLE
Websockets Connection Issues Error Code 32109 java.io.EOFException

### ISSUE THREAD

**Issue by TechnologyRonin** [eclipse/mosquitto#397]
My config is as follows:
- Raspberry Pi3, Raspbian OS
- Home Assistant All-in-One Installer (included Mosquitto)
- Home Assistant secured with Let'sEncrypt certificates (https://home-assistant.io/blog/2015/12/13/setup-encryption-using-lets-encrypt/), working perfectly
- Mosquitto server working perfectly unencrypted (no websockets) over port 1883

**mosquitto.conf file:**
```
pid_file /var/run/mosquitto.pid
user mosquitto
port 1883
listener 9001
protocol websockets
cafile /etc/ssl/certs/DST_Root_CA_X3.pem
certfile /etc/mosquitto/certs/something.com.crt
keyfile /etc/mosquitto/certs/something.com.key
persistence true
persistence_file mosquitto.db
persistence_location /var/lib/mosquitto/
password_file /etc/mosquitto/pwfile
```
**Error message from MQTT.fx when connecting using the websockets port 9001 and TLS 1.2:**

```
2017-03-07 16:02:43,396  INFO --- BrokerConnectorController      : onConnect
2017-03-07 16:02:43,400  INFO --- ScriptsController              : Clear console.
2017-03-07 16:02:43,402  INFO --- MqttFX ClientModel             : MqttClient with ID SOMETHINGHERE assigned.
2017-03-07 16:02:44,612 ERROR --- MqttFX ClientModel             : Error when connecting
org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(Unknown Source) ~[?:1.8.0_112]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	... 1 more
2017-03-07 16:02:44,620 ERROR --- MqttFX ClientModel             : Please verify your Settings (e.g. Broker Address, Broker Port & Client ID) and the user credentials!
org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(Unknown Source) ~[?:1.8.0_112]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	... 1 more
2017-03-07 16:02:44,622  INFO --- ScriptsController              : Clear console.
2017-03-07 16:02:44,623 ERROR --- BrokerConnectService           : Connection lost
```
**Error message from OwnTracks:** 
```
java.lang.Exception: Connection lost (32109) - java.io.EOFException
```
**This may be an issue with WebSockets, as I get the following error from MQTT.fx when trying to use port 9001 with no SSL/TLS (items commented out in the config file and service restarted):**
```
2017-03-07 20:26:11,595 ERROR --- MqttFX ClientModel             : Error when connecting
org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source) ~[?:1.8.0_112]
	at java.net.SocketInputStream.read(Unknown Source) ~[?:1.8.0_112]
	at java.net.SocketInputStream.read(Unknown Source) ~[?:1.8.0_112]
	at java.io.DataInputStream.readByte(Unknown Source) ~[?:1.8.0_112]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	... 1 more
2017-03-07 20:26:11,596 ERROR --- MqttFX ClientModel             : Please verify your Settings (e.g. Broker Address, Broker Port & Client ID) and the user credentials!
org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source) ~[?:1.8.0_112]
	at java.net.SocketInputStream.read(Unknown Source) ~[?:1.8.0_112]
	at java.net.SocketInputStream.read(Unknown Source) ~[?:1.8.0_112]
	at java.io.DataInputStream.readByte(Unknown Source) ~[?:1.8.0_112]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	... 1 more
2017-03-07 20:26:11,613  INFO --- ScriptsController              : Clear console.
2017-03-07 20:26:11,613 ERROR --- BrokerConnectService           : Connection lost
```
Connecting to the websockets port over SSL/TLS "works", kind of.  **Some data comes in!**  I get post data from my devices that are connecting into the WebSockets port 9001, but it's unable to maintain a connection, so I get "bursts" of data coming in that's queued up at my device (inconsistent).

It's not the username/password (that works), and it seems to be related to the WebSockets.

**Comment by hardillb** [comment]
What happens if you comment out the `protocol websockets` line?

I ask this to check if the clients you are using actually support MQTT over websockets or only native MQTT

**Comment by TechnologyRonin** [comment]
> What happens if you comment out the protocol websockets line?
> 
> I ask this to check if the clients you are using actually support MQTT over websockets or only native MQTT

As mentioned above, communication (not TLS/SSL) over native MQTT on port 1883 works perfectly.  One of the clients is MQTT.fx, and the other is OwnTracks (for Android).  I'm 100% that OwnTracks supports Websockets, since there's a toggle to use it or not.

**Comment by TechnologyRonin** [comment]
Ok, so I turned off websockets, and everything works great! So...what's the issue with WebSockets?

**Comment by binarybucks** [comment]
@TechnologyRonin is correct. 
We're seeing connection errors from the Paho Java client which loses the websocket connection shortly after connecting. The disconnect happens shortly after the CONNACK. The issue happens independently of any subscriptions, publishes or TLS settings. Connections for normal MQTT connections work fine. 

There are more details including a TCP dump over at https://github.com/owntracks/android/issues/448. 
@hardillb, could you look at the reports if anything comes to your mind?

**Comment by ralight** [comment]
According to owntracks/android#448 it looks like this was a bug in the Java client, so I'm closing this. If there is anything new to add, please reopen the bug.
