### ISSUE TITLE
Build succeeds on Debian 9 / arm64, but test 06-bridge-b2br-remapping.py fails

### ISSUE THREAD

**Issue by vielmetti** [eclipse/mosquitto#816]
System is Debian 9 on Cavium ThunderX (96-core arm64), a Packet c1.large.arm system. 

I was able to do a complete build of `branch v1.5`
after installing these dependencies:

```
apt-get install libssl-dev uuid-dev xsltproc docbook docbook-xsl
```

and then did `make test`, failing here:

```
./06-bridge-b2br-remapping.py
1526331799: mosquitto version 1.5 starting
1526331799: Config loaded from 06-bridge-b2br-remapping.conf.
1526331799: Opening ipv4 listen socket on port 1889.
1526331799: Opening ipv6 listen socket on port 1889.
1526331799: Connecting bridge bridge_sample (localhost:1888)
1526331799: Bridge debian9.worksonarm.com.bridge_sample sending CONNECT
1526331799: Error creating bridge: Connection refused.
1526331799: Warning: Unable to connect to bridge bridge_sample.
1526331799: New connection from ::1 on port 1889.
1526331799: Socket error on client <unknown>, disconnecting.
1526331803: mosquitto version 1.5 terminating

Traceback (most recent call last):
  File "./06-bridge-b2br-remapping.py", line 111, in <module>
    (bridge, address) = ssock.accept()
  File "/usr/lib/python2.7/socket.py", line 206, in accept
    sock, addr = self._sock.accept()
socket.timeout: timed out
Makefile:76: recipe for target '06' failed
```

**Comment by vielmetti** [comment]
The issue that's suspiciously similar is #507

**Comment by toast-uz** [comment]
Closing as duplicate with #890 . Sorry this issue is original, but I'd like to keep #890 due to further discussion.
